import type { Metadata } from 'next'
import LegalPage, { LegalSection as Section } from '../LegalPage'
export const metadata: Metadata = { title: 'Senthia — Privacy Policy', description: 'How Senthia handles preferences, reflections and content downloads.' }
export default function SenthiaPrivacy() {
  return <LegalPage title="Senthia Privacy Policy">
    <Section title="About this policy"><p>This policy describes the Senthia guided-imagination relaxation app operated by Althia Studios. It is specific to Senthia; other Althia apps may handle information differently.</p><p>Contact Althia Studios at <a href="mailto:althiastudios@gmail.com">althiastudios@gmail.com</a>.</p></Section>
    <Section title="Your choices and reflections"><p>Senthia does not require you to enter an email address or create a password. It creates an anonymous Firebase account to store your five free-journey selections under a randomly assigned user identifier, along with creation and update timestamps. Your language, onboarding answers, saved journeys, listening position and appearance preferences remain on your device. Recommendations are selected on your device using your answers and the available catalogue.</p><p>Optional feeling check-ins and reflections you choose to write are stored on your device. The current app does not upload your reflection text, onboarding answers or listening history to Althia’s Firebase database. Your device or operating-system backup settings may include app data in backups; this is separate from Senthia providing account sync.</p></Section>
    <Section title="Content downloads and connection information"><p>Senthia uses Google Firebase Cloud Firestore and Cloud Storage to retrieve the published journey catalogue, narration and artwork. Downloaded content and catalogue information are cached on your device so they can be reused.</p><p>These network requests necessarily share connection information, such as your IP address and the requested resource, with the service delivering the content. Requests for particular audio or artwork can identify which content is being retrieved. This is distinct from uploading your private notes or maintaining an account-based listening profile.</p><p>Google’s processing is described in <a href="https://firebase.google.com/support/privacy">Firebase’s privacy documentation</a>.</p></Section>
    <Section title="Subscriptions"><p>Apple handles App Store subscription payments. Althia does not receive your full payment-card details. Senthia uses Apple StoreKit through react-native-iap to retrieve available products, process purchases and restore access. The app reads subscription product identifiers, transaction status and expiry information, and securely caches expiry information on your device.</p><p>The current integration does not send purchase receipts or transaction history to Althia’s Firebase database or to a separate subscription-management provider. Purchases are available only where enabled in the app and App Store.</p></Section>
    <Section title="Analytics, advertising and health information"><p>The current Senthia app does not initialize an advertising SDK or Firebase Analytics, and does not upload behavioral analytics through its own application code. Infrastructure providers may still process operational connection information as described above.</p><p>The current app does not request HealthKit access or collect heart-rate measurements. If an optional health feature is introduced, we will describe the information involved and request the relevant permissions before accessing it.</p></Section>
    <Section title="Support"><p>If you contact <a href="mailto:althiastudios@gmail.com">althiastudios@gmail.com</a>, we receive the email address and information you send. We use that information to respond and troubleshoot. You do not need to include private reflection text in a support request.</p></Section>
    <Section title="Managing and deleting information"><p>You can change preferences in Your space and delete individual reflections from the reflection editor. Removing the app removes its ordinary local app data, subject to operating-system backup and restore behavior. Anonymous sign-in credentials are kept in secure device storage and may remain in the iOS Keychain after uninstalling. Uninstalling does not delete the free-journey record held in Firebase. Contact support to request deletion of that record; we may need to verify which record belongs to you. Cached audio may also be removed by the operating system.</p><p>Uninstalling the app does not cancel an App Store subscription. Subscriptions must be managed through Apple. For information you have sent directly to support, contact us to request access, correction or deletion, subject to applicable retention requirements.</p></Section>
    <Section title="Rights and retention"><p>Local preferences and reflections remain on your device until removed, subject to device backup and restore settings. The anonymous identifier and free-journey selections are retained to maintain your free collection until the record is deleted following a verified request or service-retention changes. Recovery on a replacement device is not guaranteed without a linked account. Support correspondence is kept for as long as needed to address your request and meet applicable legal obligations. Operational infrastructure records follow the service provider’s applicable retention practices; this policy does not promise a fixed deletion period for those records.</p><p>Depending on where you live, you may have rights to access, correct, delete or receive your personal information, restrict or object to processing, and complain to the relevant privacy authority. Contact support to exercise those rights. We cannot retrieve reflection text that exists only on your device.</p></Section>
    <Section title="Processing and service providers"><p>We use the information described above to deliver requested content, respond to support requests and maintain the service. Where data-protection law requires a legal basis, this may be performance of the requested service, legitimate interests in operating and securing it, compliance with legal obligations, or consent where required.</p><p>Service providers may process information outside your country. Applicable data-protection safeguards, including those described in Google’s Firebase documentation, govern relevant transfers. Senthia does not sell your reflection text or use it for advertising.</p></Section>
    <Section title="Changes and contact"><p>We will update this policy when Senthia’s data practices change and provide notice appropriate to the change. Where required, we will request consent before beginning new processing. Questions can be sent to <a href="mailto:althiastudios@gmail.com">althiastudios@gmail.com</a>.</p></Section>
  </LegalPage>
}
