import type { Metadata } from 'next'
import LegalPage, { LegalSection as Section } from '../LegalPage'
export const metadata: Metadata = { title: 'Senthia — Privacy Policy (Draft)', description: 'How Senthia handles preferences, reflections and content downloads.', robots: { index: false, follow: false } }
export default function SenthiaPrivacy() {
  return <LegalPage title="Senthia Privacy Policy">
    <Section title="About this policy"><p>This policy describes the Senthia guided-imagination relaxation app operated by Althia Studios. It is specific to Senthia; other Althia apps may handle information differently.</p><p>Contact Althia Studios at <a href="mailto:support@althia.org">support@althia.org</a>.</p></Section>
    <Section title="Your choices and reflections"><p>Senthia currently works without an account. Your language, onboarding answers, saved journeys, free-journey selections, listening position and appearance preferences are stored on your device. Recommendations are selected on your device using your answers and the available catalogue.</p><p>Reflections you choose to write are stored on your device. The current app does not upload your reflection text, onboarding answers or listening history to Althia’s Firebase database. Your device or operating-system backup settings may include app data in backups; this is separate from Senthia providing account sync.</p></Section>
    <Section title="Content downloads and connection information"><p>Senthia uses Google Firebase Cloud Firestore and Cloud Storage to retrieve the published journey catalogue, narration and artwork. Downloaded content and catalogue information are cached on your device so they can be reused.</p><p>These network requests necessarily share connection information, such as your IP address and the requested resource, with the service delivering the content. Requests for particular audio or artwork can identify which content is being retrieved. This is distinct from uploading your private notes or maintaining an account-based listening profile.</p><p>Google’s processing is described in <a href="https://firebase.google.com/support/privacy">Firebase’s privacy documentation</a>.</p></Section>
    <Section title="Subscriptions"><p>Purchases are not enabled in the current preview. When App Store subscriptions become available, Apple will handle payment. Althia will not receive your full payment-card details. The app will need purchase-status information to determine subscription access and restore purchases.</p><p>This section will be updated before purchases launch to identify any subscription provider or server-side transaction processing actually used. The preview does not process payments.</p></Section>
    <Section title="Analytics, advertising and health information"><p>The current Senthia app does not initialize an advertising SDK or Firebase Analytics, and does not upload behavioral analytics through its own application code. Infrastructure providers may still process operational connection information as described above.</p><p>The current app does not request HealthKit access or collect heart-rate measurements. If an optional health feature is introduced, we will describe the information involved and request the relevant permissions before accessing it.</p></Section>
    <Section title="Support"><p>If you contact <a href="mailto:support@althia.org">support@althia.org</a>, we receive the email address and information you send. We use that information to respond and troubleshoot. You do not need to include private reflection text in a support request.</p></Section>
    <Section title="Managing and deleting information"><p>You can change preferences in Your space and delete individual reflections from the reflection editor. Removing the app removes its local app data, subject to operating-system backup and restore behavior. Cached audio may also be removed by the operating system.</p><p>Uninstalling the app does not cancel an App Store subscription. Subscriptions must be managed through Apple. For information you have sent directly to support, contact us to request access, correction or deletion, subject to applicable retention requirements.</p></Section>
    <Section title="Rights and retention"><p>Depending on where you live, you may have rights to access, correct, delete or receive your personal information, restrict or object to processing, and complain to the relevant privacy authority. Contact support to exercise those rights. We cannot retrieve reflection text that exists only on your device.</p></Section>
    <Section title="Changes and contact"><p>We will update this policy when Senthia’s data practices change and provide notice appropriate to the change. Where required, we will request consent before beginning new processing. Questions can be sent to <a href="mailto:support@althia.org">support@althia.org</a>.</p></Section>
  </LegalPage>
}
