import type { Metadata } from 'next'
import Link from 'next/link'
import LegalPage, { LegalSection as Section } from '../LegalPage'
export const metadata: Metadata = { title: 'Senthia — Terms of Use (Draft)', description: 'Terms for Senthia guided-imagination journeys and subscriptions.', robots: { index: false, follow: false } }
export default function SenthiaTerms() {
  return <LegalPage title="Senthia Terms of Use">
    <Section title="About Senthia"><p>Senthia is a guided-imagination relaxation app operated by Althia Studios. It offers narrated imagined places, artwork and listening features. These terms apply to Senthia, not to purchases in other Althia apps.</p></Section>
    <Section title="Using the app"><p>You may use Senthia and its content for personal, non-commercial listening. Access does not transfer ownership of the recordings, artwork or other app content. You may not redistribute or commercially exploit that content without permission, except where applicable law permits it.</p><p>Use the app in a setting where you can safely relax. Do not use immersive listening while driving or doing something that requires your full attention.</p></Section>
    <Section title="Monthly and annual subscriptions"><p>Senthia’s planned paid offering consists of monthly and annual auto-renewing subscriptions. There are no lifetime purchases or ownership packs. Purchases are not available in the current preview.</p><p>When subscriptions are enabled, the purchase screen and Apple’s confirmation sheet will show the price, currency, billing period and any applicable offer before you confirm. An annual subscription is billed for the full year, rather than as twelve monthly payments. Do not assume a free trial unless one is expressly offered to you.</p><p>Subscriptions provide access to the included collection while active. Narration languages and sound modes vary by journey; purchasing a subscription does not make an unavailable language or mode available. Future content does not have a guaranteed release cadence unless expressly stated.</p></Section>
    <Section title="Renewal, cancellation and restoration"><p>Subscriptions renew automatically unless you cancel. You can manage or cancel through your Apple Account subscription settings. Follow the cancellation timing shown by Apple for your subscription. Removing Senthia from your device does not cancel a subscription.</p><p>Unless Apple’s subscription status or applicable law provides otherwise, cancelling stops future renewal and access continues until the paid period ends. Restore purchases will check eligible purchases associated with the Apple Account used to buy the subscription.</p><p>Apple processes App Store payments and refund requests. You can request a refund at <a href="https://reportaproblem.apple.com">reportaproblem.apple.com</a>. Nothing in these terms removes mandatory consumer rights or statutory remedies.</p></Section>
    <Section title="Preferences and reflections"><p>The current app does not require an account. Your preferences and optional reflections are stored on your device. You retain rights to the reflections you write; saving one does not publish it or grant Althia permission to use its text as app content.</p><p>Local data can be lost when the app is removed or device data is lost. See the <Link href="/senthia/privacy">Senthia Privacy Policy</Link> for current storage and network practices.</p></Section>
    <Section title="Relaxation, not medical treatment"><p>Senthia provides a relaxation experience. It is not a medical service and does not diagnose, treat or promise to prevent a health condition. Individual experiences differ, and no particular emotional or physiological result is guaranteed. Stop or choose a different journey if an experience feels uncomfortable.</p><p>Heart-rate tracking is not part of the current app. Any future health-related feature will have its own explanation and applicable permissions before use.</p></Section>
    <Section title="Content and availability"><p>Althia or its licensors hold rights to Senthia’s app content and branding. The collection and features may evolve. We will describe material changes affecting a paid service and respect the notice, refund and other rights required by applicable law.</p><p>Downloads depend on a connection and available device storage. Content cached for offline listening does not grant permanent ownership.</p></Section>
    <Section title="Consumer protections and applicable law"><p>Nothing in these terms excludes rights or liabilities that cannot lawfully be excluded. Mandatory consumer protections continue to apply regardless of other provisions in these terms.</p></Section>
    <Section title="Changes and contact"><p>Material changes to these terms will be communicated as appropriate, with consent obtained where required. Contact <a href="mailto:support@althia.org">support@althia.org</a> with questions about Senthia.</p></Section>
  </LegalPage>
}
